disabled_rules: # rule identifiers to exclude from running
- superfluous_disable_command
- trailing_whitespace
- line_length
- identifier_name

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods

# add custom criteria for ruler
function_body_length:
 - 60 # warning
 - 100 # error
