workflows:
  ios-workflow:
    name: RAWGCatalog Workflow
    environment:
        xcode: 13.3.1
        cocoapods: default # <-- You can using specific version of cocoapods, ex: 1.10.2
        vars:
            GAME_XCODE_SCHEME: "GameModule"
            GENRE_XCODE_SCHEME: "GenreModule"
            STORE_XCODE_SCHEME: "StoreModule"
            ABOUT_XCODE_SCHEME: "AboutModule"
            MAIN_XCODE_SCHEME: "RAWGCatalog"
            XCODE_WORKSPACE: "Main/RAWGCatalog.xcworkspace"
            PROJECT_PATH: "Main"
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install --project-directory=$PROJECT_PATH
      - name: Test GameModule
        script: |
          xcode-project run-tests --workspace "$XCODE_WORKSPACE" --scheme "$GAME_XCODE_SCHEME"
        test_report: build/ios/test/*.xml
      - name: Test GenreModule
        script: |
          xcode-project run-tests --workspace "$XCODE_WORKSPACE" --scheme "$GENRE_XCODE_SCHEME"
        test_report: build/ios/test/*.xml
      - name: Test StoreModule
        script: |
          xcode-project run-tests --workspace "$XCODE_WORKSPACE" --scheme "$STORE_XCODE_SCHEME"
        test_report: build/ios/test/*.xml
      - name: Test AboutModule
        script: |
          xcode-project run-tests --workspace "$XCODE_WORKSPACE" --scheme "$ABOUT_XCODE_SCHEME"
        test_report: build/ios/test/*.xml
      - name: Test RAWGCatalog
        script: |
          xcode-project run-tests --workspace "$XCODE_WORKSPACE" --scheme "$MAIN_XCODE_SCHEME"
        test_report: build/ios/test/*.xml
    artifacts:
      - build/ios/test/*.xml
    publishing:
      email:
        recipients:
            - intan3951@gmail.com
        notify:
            success: true # To receive a notification when a build succeeds
            failure: true # To receive a notification when a build fails
