name: RAWG Workflow

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Installing dependencies
        run:  pod install
      - name: Build and Test
        run:  xcodebuild test -workspace Main/RAWGCatalog.xcworkspace -scheme RAWGCatalog -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=15.2' build test
